const userPosts = [
  {
    firstName: "Allison",
    lastName: "Becker",
    location: "New York, NY",
    likes: 1201,
    comments: 24,
    bookmarks: 55,
    image: require("./assets/images/default_profile.png"),
    profileImage: require("./assets/images/default_post.png"),
    id: 1,
  },
  {
    firstName: "Jennifer",
    lastName: "Wright",
    location: "New York, NY",
    likes: 1301,
    comments: 27,
    bookmarks: 57,
    image: require("./assets/images/default_profile.png"),
    profileImage: require("./assets/images/default_post.png"),
    id: 2,
  },
  {
    firstName: "David",
    lastName: "king",
    location: "New York, NY",
    likes: 1401,
    comments: 30,
    bookmarks: 51,
    image: require("./assets/images/default_profile.png"),
    profileImage: require("./assets/images/default_post.png"),
    id: 3,
  },
  {
    firstName: "John",
    lastName: "Davis",
    location: "New York, NY",
    likes: 1101,
    comments: 12,
    bookmarks: 59,
    image: require("./assets/images/default_profile.png"),
    profileImage: require("./assets/images/default_post.png"),
    id: 4,
  },
  {
    firstName: "Sarah",
    lastName: "Miller",
    location: "New York, NY",
    likes: 600,
    comments: 20,
    bookmarks: 60,
    image: require("./assets/images/default_profile.png"),
    profileImage: require("./assets/images/default_post.png"),
    id: 5,
  },
];

export default userPosts